### ISSUE TITLE
Clean UI inconsistencies

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#382]
Here's the list of UI issues left to fix (thanks @LeeAlephium !):

- [x] Don't display outlines on click, but continue to display them when selected with tab (accessibility) (https://github.com/alephium/desktop-wallet/issues/378#issuecomment-1261351090)
- [x] Increase spacing between input fields (https://github.com/alephium/desktop-wallet/issues/378#issuecomment-1261400865)
- [x] Change recovery phrase message to "Make sure to *store* the words in a secure location..." (https://github.com/alephium/desktop-wallet/issues/378#issuecomment-1261430921) French translation is already correct.
- [x] Increase line height a bit on paragraphe (like the one mentioned here https://github.com/alephium/desktop-wallet/issues/378#issuecomment-1261430921)

**Comment by nop33** [comment]
Closing since it's done by #386
